clients.pokeapi.base-url=${POKEAPI_BASE_URL}
clients.pokeapi.species-path=${POKEAPI_SPECIES_PATH}

clients.translations.base-url=${TRANSLATIONS_BASE_URL}
clients.translations.yoda-path=${TRANSLATIONS_YODA_PATH}
clients.translations.shakespeare-path=${TRANSLATIONS_SHAKESPEARE_PATH}

logging.level.root=INFO
logging.level.com.truelayer.pokedex=INFO