clients.pokeapi.base-url=https://pokeapi.co/api/v2
clients.pokeapi.species-path=/pokemon-species/{name}

clients.translations.base-url=https://api.funtranslations.mercxry.me
clients.translations.yoda-path=/v1/translate/yoda
clients.translations.shakespeare-path=/v1/translate/shakespeare

logging.level.root=INFO
logging.level.com.truelayer.pokedex=DEBUG